/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#6fd8c8",
        "on-primary": "#003731",
        "primary-fixed": "#8cf5e4",
        "primary-fixed-dim": "#6fd8c8",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005048",
        "primary-container": "#00211d",
        "on-primary-container": "#1a9486",
        secondary: "#98cdf2",
        "on-secondary": "#00344c",
        "secondary-fixed": "#c7e7ff",
        "secondary-fixed-dim": "#98cdf2",
        "on-secondary-fixed": "#001e2e",
        "on-secondary-fixed-variant": "#064c6b",
        "secondary-container": "#0b4e6e",
        "on-secondary-container": "#8abfe4",
        tertiary: "#ffb3b1",
        "on-tertiary": "#680011",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b1",
        "on-tertiary-fixed": "#410007",
        "on-tertiary-fixed-variant": "#92001c",
        "tertiary-container": "#410007",
        "on-tertiary-container": "#f1414d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        surface: "#111125",
        "surface-dim": "#111125",
        "surface-bright": "#37374d",
        "surface-container-lowest": "#0c0c1f",
        "surface-container-low": "#1a1a2e",
        "surface-container": "#1e1e32",
        "surface-container-high": "#28283d",
        "surface-container-highest": "#333348",
        "surface-variant": "#333348",
        "surface-tint": "#6fd8c8",
        "on-surface": "#e2e0fc",
        "on-surface-variant": "#c8c5cd",
        "inverse-surface": "#e2e0fc",
        "inverse-on-surface": "#2f2e43",
        "inverse-primary": "#006a60",
        background: "#111125",
        "on-background": "#e2e0fc",
        outline: "#929097",
        "outline-variant": "#47464c",
        "accent-purple": "#7c3aed",
        "accent-cyan": "#22d3ee",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.5s ease-out forwards",
        "scale-in": "scaleIn 0.4s ease-out forwards",
        "slide-in-right": "slideInRight 0.4s ease-out forwards",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        spin: "spin 1s linear infinite",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
};
